# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
#
# Workflow to automatedly build all packages

name: Build All Packages

on:
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.13
      id: go

    - name: Checkout
      uses: actions/checkout@v2.3.2
      with:
        ref: '0146aa2ee961950f10fe8a3b3adf163cfaa96baf'
        
    - name: Build All Packages
      run: |
        sudo apt -y install make tar wget curl rpm qemu-utils genisoimage pigz
        pushd toolkit
        sudo make build-packages -j$(nproc) CONFIG_FILE= DOWNLOAD_SRPMS=y REBUILD_TOOLS=y
