# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# Sync fork branch with upstream

name: Sync Fork Branch with Upstream

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      branchname:
        description: 'Branch to sync'
        default: 'main'
        required: false

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.2
      with:
        ref: ${{ github.event.inputs.branchname }}
    - name: Sync
      run: |
        git checkout ${{ github.event.inputs.branchname }}
        git remote add upstream https://github.com/microsoft/CBL-Mariner.git
        git fetch upstream
        git pull upstream ${{ github.event.inputs.branchname }}
        git push origin ${{ github.event.inputs.branchname }}
